# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [ dev, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
    - run: npm install -g mocha
    - run: npm install -g typescript
    - run: npm install -g ts-node
    - run: npm install
#    - run: npm audit fix  /* swagger-tools 보완 취약점 존재. Swagger-tools 제거하고 주석 해제 해야함. */
#    - run: npm ci
#    - run: npm run build --if-present
    - name: run test code 
      run: npm test
      env:
        NODE_ENV: test
        MYSQL_TST_USERNAME: '${{ secrets.MYSQL_TST_USERNAME }}'
        MYSQL_TST_PASSWORD: '${{ secrets.MYSQL_TST_PASSWORD }}'
        MYSQL_TST_DATABASE: '${{ secrets.MYSQL_TST_DATABASE }}'
        MYSQL_TST_HOST: '${{ secrets.MYSQL_TST_HOST }}'
        MYSQL_TST_PORT: '${{ secrets.MYSQL_TST_PORT }}'
        MYSQL_TST_DIALECT: '${{ secrets.MYSQL_TST_DIALECT }}'
        MONGO_URI: '${{ secrets.MONGO_URI }}'
        CORS_ALLOW_LIST: '${{ secrets.CORS_ALLOW_LIST }}'
        JWT_SECRET: '${{ secrets.JWT_SECRET }}'
        AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
        AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY}}'
        ENCRYPTION_KEY: '${{ secrets.ENCRYPTION_KEY }}'
        ENCRYPT_ALGORITHM: '${{ secrets.ENCRYPT_ALGORITHM }}'
        AWS_S3_URL: '${{ secrets.AWS_S3_URL }}'
